# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: NetSarangComputer,Inc.Xftp8
PackageVersion: 8.0.0068
PackageLocale: en-US
Publisher: NetSarang Computer, Inc.
PackageName: Xftp 8
License: MIT
Copyright: NetSarang Computer, Inc.
ShortDescription: Xftp Installer
ManifestType: defaultLocale
ManifestVersion: 1.9.0
