# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Resilio.ResilioSync
PackageVersion: 3.0.3.1065
PackageLocale: en-US
Publisher: Resilio, Inc.
PackageName: Resilio Sync
License: MIT License
Copyright: Copyright (C) 2025 Resilio, Inc. All Rights Reserved.
ShortDescription: Resilio Sync
ManifestType: defaultLocale
ManifestVersion: 1.9.0
